'use strict';

// تولیدشده خودکار از کد ۸۶ قرارداد — نگاشت تابع نوشتنی و پارامترهای هر قرارداد
//
// needsSeed: قراردادهای مکانی که سلول سرویس‌دهنده را خودشان انتخاب می‌کنند و
// پیش از هر نوشتنی به SeedNetwork نیاز دارند تا چیدمان آنتن موجود باشد.
// antennaDep دیگر در هیچ قراردادی true نیست: هفت قرارداد قفل‌شده حالا از
// طریق SeedNetwork بذرکاری می‌شوند به‌جای اینکه رکورد آنتنی بخواهند که فقط
// خودشان می‌توانستند بسازند.
const CONTRACT_FN = {
  AllocateResource: { fn: 'Allocate', params: ["entityID","resource","amount"], antennaDep: false, needsSeed: false },
  AssignRole: { fn: 'Assign', params: ["userID","role"], antennaDep: false, needsSeed: false },
  AuthenticateIoT: { fn: 'Authenticate', params: ["deviceID","token"], antennaDep: false, needsSeed: false },
  AuthenticateUser: { fn: 'Authenticate', params: ["userID","token"], antennaDep: false, needsSeed: false },
  BalanceLoad: { fn: 'Balance', params: ["networkID","load"], antennaDep: false, needsSeed: false },
  ConnectIoT: { fn: 'Connect', params: ["deviceID","antennaID"], antennaDep: false, needsSeed: false },
  ConnectUser: { fn: 'Connect', params: ["userID","antennaID"], antennaDep: false, needsSeed: false },
  DecryptData: { fn: 'Decrypt', params: ["entityID","data"], antennaDep: false, needsSeed: false },
  EncryptData: { fn: 'Encrypt', params: ["entityID","data"], antennaDep: false, needsSeed: false },
  LocationBasedAntennaConfig: { fn: 'SetAntennaConfig', params: ["antennaID","config","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedAssignment: { fn: 'AssignAntenna', params: ["entityID","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedBandwidth: { fn: 'AssignBandwidth', params: ["entityID","bandwidth","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedChannelAllocation: { fn: 'AllocateChannel', params: ["entityID","channelID","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedCongestion: { fn: 'RecordCongestion', params: ["entityID","congestion","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedConnection: { fn: 'ConnectEntity', params: ["entityID","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedCoverage: { fn: 'RecordCoverage', params: ["entityID","coverage","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedDynamicRouting: { fn: 'SetDynamicRoute', params: ["entityID","route","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedEnergy: { fn: 'RecordEnergy', params: ["entityID","energy","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedFault: { fn: 'ReportFault', params: ["entityID","faultType","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedInterference: { fn: 'RecordInterference', params: ["entityID","interferenceLevel","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTAuthentication: { fn: 'AuthenticateIoT', params: ["deviceID","token","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTBandwidth: { fn: 'AllocateIoTBandwidth', params: ["deviceID","bandwidth","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTConnection: { fn: 'ConnectIoT', params: ["deviceID","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTFault: { fn: 'ReportIoTFault', params: ["deviceID","faultType","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTRegistration: { fn: 'RegisterIoT', params: ["deviceID","status","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTResource: { fn: 'AllocateIoTResource', params: ["deviceID","resourceID","amount","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTRevocation: { fn: 'RevokeIoT', params: ["deviceID","status","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTSession: { fn: 'StartIoTSession', params: ["deviceID","sessionID","status","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedIoTStatus: { fn: 'UpdateIoTStatus', params: ["deviceID","status","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedLatency: { fn: 'RecordLatency', params: ["entityID","latency","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedNetworkHealth: { fn: 'RecordNetworkHealth', params: ["entityID","healthStatus","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedNetworkLoad: { fn: 'RecordNetworkLoad', params: ["entityID","load","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedPowerManagement: { fn: 'SetPowerLevel', params: ["entityID","powerLevel","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedPriority: { fn: 'AssignPriority', params: ["entityID","priority","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedQoS: { fn: 'AssignQoS', params: ["entityID","qosLevel","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedResourceAllocation: { fn: 'AllocateResource', params: ["entityID","resourceID","amount","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedRoaming: { fn: 'PerformRoaming', params: ["entityID","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedSessionManagement: { fn: 'ManageSession', params: ["entityID","sessionID","status","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedSignalQuality: { fn: 'RecordSignalQuality', params: ["entityID","signalQuality","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedSignalStrength: { fn: 'RecordSignalStrength', params: ["entityID","signal","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedStatus: { fn: 'UpdateStatus', params: ["entityID","status","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedTraffic: { fn: 'RecordTraffic', params: ["entityID","traffic","x","y","seed"], antennaDep: false, needsSeed: true },
  LocationBasedUserActivity: { fn: 'RecordUserActivity', params: ["userID","activity","x","y","seed"], antennaDep: false, needsSeed: true },
  LogAccessAudit: { fn: 'Log', params: ["entityID","action"], antennaDep: false, needsSeed: false },
  LogAccessControl: { fn: 'Log', params: ["entityID","action"], antennaDep: false, needsSeed: false },
  LogAntennaAudit: { fn: 'Log', params: ["antennaID","action"], antennaDep: false, needsSeed: false },
  LogComplianceAudit: { fn: 'Log', params: ["entityID","complianceStatus"], antennaDep: false, needsSeed: false },
  LogConnectionAudit: { fn: 'Log', params: ["entityID","antennaID","action"], antennaDep: false, needsSeed: false },
  LogFault: { fn: 'LogFault', params: ["entityID","faultType"], antennaDep: false, needsSeed: false },
  LogInterference: { fn: 'LogInterference', params: ["entityID","interferenceLevel"], antennaDep: false, needsSeed: false },
  LogIoTActivity: { fn: 'Log', params: ["deviceID","activity"], antennaDep: false, needsSeed: false },
  LogIoTAudit: { fn: 'Log', params: ["deviceID","action"], antennaDep: false, needsSeed: false },
  LogNetworkAudit: { fn: 'Log', params: ["networkID","action"], antennaDep: false, needsSeed: false },
  LogNetworkPerformance: { fn: 'Log', params: ["networkID","metric","value"], antennaDep: false, needsSeed: false },
  LogPerformance: { fn: 'LogPerformance', params: ["entityID","metric","value"], antennaDep: false, needsSeed: false },
  LogPerformanceAudit: { fn: 'Log', params: ["entityID","metric","value"], antennaDep: false, needsSeed: false },
  LogPolicyAudit: { fn: 'Log', params: ["policyID","action"], antennaDep: false, needsSeed: false },
  LogPolicyChange: { fn: 'Log', params: ["policyID","change"], antennaDep: false, needsSeed: false },
  LogResourceAudit: { fn: 'LogResourceAudit', params: ["entityID","resource","amount"], antennaDep: false, needsSeed: false },
  LogSecurityAudit: { fn: 'Log', params: ["entityID","event"], antennaDep: false, needsSeed: false },
  LogSecurityEvent: { fn: 'Log', params: ["entityID","event"], antennaDep: false, needsSeed: false },
  LogSession: { fn: 'LogSession', params: ["entityID","sessionID","status"], antennaDep: false, needsSeed: false },
  LogSessionAudit: { fn: 'Log', params: ["entityID","sessionID","action"], antennaDep: false, needsSeed: false },
  LogTraffic: { fn: 'LogTraffic', params: ["entityID","traffic"], antennaDep: false, needsSeed: false },
  LogUserActivity: { fn: 'Log', params: ["userID","activity"], antennaDep: false, needsSeed: false },
  LogUserAudit: { fn: 'Log', params: ["userID","action"], antennaDep: false, needsSeed: false },
  ManageAntenna: { fn: 'UpdateAntennaStatus', params: ["antennaID","status"], antennaDep: false, needsSeed: false },
  ManageIoTDevice: { fn: 'UpdateDeviceStatus', params: ["deviceID","status"], antennaDep: false, needsSeed: false },
  ManageNetwork: { fn: 'UpdateNetworkStatus', params: ["networkID","status"], antennaDep: false, needsSeed: false },
  ManageSession: { fn: 'StartSession', params: ["entityID","sessionID"], antennaDep: false, needsSeed: false },
  ManageUser: { fn: 'UpdateUserStatus', params: ["userID","status"], antennaDep: false, needsSeed: false },
  MonitorInterference: { fn: 'RecordInterference', params: ["networkID","interferenceLevel"], antennaDep: false, needsSeed: false },
  MonitorIoT: { fn: 'RecordStatus', params: ["deviceID","status"], antennaDep: false, needsSeed: false },
  MonitorNetwork: { fn: 'RecordStatus', params: ["networkID","status"], antennaDep: false, needsSeed: false },
  MonitorResourceUsage: { fn: 'RecordUsage', params: ["entityID","resource","amount"], antennaDep: false, needsSeed: false },
  MonitorTraffic: { fn: 'RecordTraffic', params: ["networkID","traffic"], antennaDep: false, needsSeed: false },
  OptimizeNetwork: { fn: 'Optimize', params: ["networkID","strategy"], antennaDep: false, needsSeed: false },
  RegisterIoT: { fn: 'Register', params: ["deviceID","status"], antennaDep: false, needsSeed: false },
  RegisterUser: { fn: 'Register', params: ["userID","status"], antennaDep: false, needsSeed: false },
  RevokeIoT: { fn: 'Revoke', params: ["deviceID","status"], antennaDep: false, needsSeed: false },
  RevokeUser: { fn: 'Revoke', params: ["userID","status"], antennaDep: false, needsSeed: false },
  SecureCommunication: { fn: 'Establish', params: ["entityID","channelID"], antennaDep: false, needsSeed: false },
  SetPolicy: { fn: 'Set', params: ["policyID","policy"], antennaDep: false, needsSeed: false },
  UpdatePolicy: { fn: 'Update', params: ["policyID","policy"], antennaDep: false, needsSeed: false },
  VerifyIdentity: { fn: 'Verify', params: ["entityID","verified"], antennaDep: false, needsSeed: false },
};

module.exports = { CONTRACT_FN };
